apiVersion: apps/v1
kind: Deployment
metadata:
    name: pgadmin-deployment
    labels:
        app: pgadmin
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pgadmin
    template:
        metadata:
            labels:
                app: pgadmin
        spec:
            containers:
                - name: pgadmin
                  image: dpage/pgadmin4:7.3
                  ports:
                      - containerPort: 80
                  env:
                      - name: PGADMIN_DEFAULT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: pgadmin-secrets
                                key: PG_PASSWORD
                      - name: PGADMIN_DEFAULT_EMAIL
                        valueFrom:
                            secretKeyRef:
                                name: pgadmin-secrets
                                key: PG_USER_EMAIL
                      - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
                        value: "False"
---
# Los 3 guiones son para separar archivos, en este caso para crear un servicio en el mismo archivo

apiVersion: v1
kind: Service
metadata:
    name: pgadmin-service
spec:
    type: NodePort
    # type: LoadBalancer
    selector:
        app: pgadmin-app
    ports:
        - protocol: TCP
          port: 80 # cualquier puerto. Puerto donde se conectaran en el closter. Se pone el mismo para que sea mas facilmente acordarse
          targetPort: 80 # puerto expuesto
          nodePort: 30200 #Tiene que estar entre 30000 y 32767
          #loadBalancer: 7001
