apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secrets
type: Opaque
data:
    # https://codebeautify.org/base64-encode
    # Base64 String : superman@google.com
    # en la terminal de MAC se podria hacer por la terminal asi -> echo -n postgres | base64
    PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
    # 123456
    PG_PASSWORD: MTIzNDU2
