apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
type: Opaque
data:
    # https://codebeautify.org/base64-encode
    # Base64 String : postgres
    # en la terminal de MAC se podria hacer por la terminal asi -> echo -n postgres | base64
    DB_USER: cG9zdGdyZXM=
    # EstoEsUnPasswordSecreto
    DB_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=
