apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
    labels:
        app: postgres
spec:
    replicas: 3
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:15.1
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secrets
                                key: DB_PASSWORD
---
# Los 3 guiones son para separar archivos, en este caso para crear un servicio en el mismo archivo

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-app
  ports:
    - protocol: TCP
      port: 5432 # cualqueir puerto. Puerto donde se conectaran. Se pone el mismo para que sea mas facilmente acordarse
      targetPort: 5432